jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run script with CLIENT_SECRET
        run: |
          python main.py
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}  # Menambahkan secret
