name: Run YouTube Bot

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (adjust as needed)
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client

      - name: Run YouTube Bot
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python main.py
