name: Run YouTube Comment Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Menjalankan setiap 5 menit
  workflow_dispatch:  # Agar bisa dijalankan secara manual jika perlu

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Versi Python yang digunakan

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run script
        run: |
          python main.py  # Skrip yang akan dijalankan
